# Dockerfile

# FROM directive instructing base image to build upon (/usr/src/app)
FROM python:2-onbuild

# COPY startup script into known file location in container
COPY start.sh /start.sh
RUN chmod +x /start.sh

# EXPOSE port 8000 to allow communication to/from server
EXPOSE 8000

# done!
