FROM    nginx:stable
EXPOSE  443

COPY ./nginx/default /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/dhparam.pem /etc/nginx/dhparam.pem
COPY ./nginx/nginx-selfsigned.crt /etc/nginx/nginx-selfsigned.crt
COPY ./nginx/nginx-selfsigned.key /etc/nginx/nginx-selfsigned.key
