# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_rentaldates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rentaldates',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='rentals.Rental'),
        ),
    ]
