# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20171218_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='insurance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
